ant test
language: java
install: ant deps
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
